spring.application.name=toolVPT

toolvpt.window-width=1496
toolvpt.window-height=936
toolvpt.window-x=0
toolvpt.window-y=0
toolvpt.region-width=320
toolvpt.region-height=180
toolvpt.max-acceptable-distance=80.0
toolvpt.min-distance-gap=10.0
toolvpt.debug-save-image=false
toolvpt.debug-image-path=debug.png
toolvpt.capture-interval-ms=300