spring.application.name=toolVPT

toolvpt.window-width=1496
toolvpt.window-height=936
toolvpt.window-x=150
toolvpt.window-y=50
toolvpt.region-width=1100
toolvpt.region-height=700
toolvpt.max-acceptable-distance=80.0
toolvpt.min-distance-gap=10.0
toolvpt.debug-save-image=false
toolvpt.debug-image-path=debug.png
toolvpt.capture-interval-ms=300

toolvpt.detect-region-x=500
toolvpt.detect-region-y=300
toolvpt.detect-region-width=200
toolvpt.detect-region-height=100

toolvpt.matcher-accept-score=30.0
toolvpt.matcher-step=2
toolvpt.matcher-max-results=10